readers:
  - "urn:github:526301"
assets:
  config.yml: yegor256/home#assets/sixnines/config.yml
  id_rsa: yegor256/home#assets/heroku-key
  id_rsa.pub: yegor256/home#assets/heroku-key.pub
install: |-
  sudo apt-get update -y
  sudo apt-get install -y libmagickwand-dev imagemagick
  sudo rvm install ruby-2.6.0
  rvm use 2.6.0
  export GEM_HOME=~/.ruby
  export GEM_PATH=$GEM_HOME:$GEM_PATH
release:
  sensitive:
    - config.yml
  script: |-
    bundle install
    bundle exec rake
    git remote add dokku dokku@www.sixnines.io:sixnines
    rm -rf ~/.ssh
    mkdir ~/.ssh
    mv ../id_rsa ../id_rsa.pub ~/.ssh
    chmod -R 600 ~/.ssh/*
    echo -e "Host *\n  StrictHostKeyChecking no\n  UserKnownHostsFile=/dev/null" > ~/.ssh/config
    git add .gitignore
    git fetch
    sed -i "s/BUILD/${tag}/g" ./version.rb
    git add ./version.rb
    git commit -m 'build number set'
    cp ../config.yml config.yml
    git add config.yml
    git commit -m 'config.yml'
    git push -f dokku $(git symbolic-ref --short HEAD):master
    git reset HEAD~1
    rm -rf config.yml
    curl -f --connect-timeout 15 --retry 5 --retry-delay 30 http://www.sixnines.io > /dev/null
  commanders:
  - yegor256
architect:
- yegor256
merge:
  commanders: []
  script: |-
    bundle install
    bundle exec rake
deploy: {}
